spring:
  application:
    name: payment-service
  datasource:
    dynamic:
      primary: offer
      datasource:
        offer:
          username: root
          password: root
          url: jdbc:mysql://127.0.0.1/ex55-spot-dev-a?useSSL=false&rewriteBatchedStatements=true
          driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
      defaultZone: http://eureka7001.com:7001/eureka

logging:
  level:
    root: info
    com.jason.springcloud: info
